#!/bin/bash
# Firstrun setup for Raspberry Pi. Copied to /etc/init.d/firstrun
### BEGIN INIT INFO
# Provides:          firstrun
# Required-Start:    
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:
### END INIT INFO

LIBNFCDIR=/home/pi/libnfc-1.7.1
MAINDIR=/home/pi/src/vnw/main
GOPATH=/home/pi/
SEMAPHORE=/var/opt/vnw-run
if [ ! -f $SEMAPHORE ]
then
	apt-get install libusb-dev daemontools vim
	cd $LIBNFCDIR
	$LIBNFCDIR/configure
	make
	make install
	cd $MAINDIR
	GOPATH=$GOPATH go build main.go
	cp main /bin/
  install scripts/lock /bin/
  install scripts/unlock /bin/
  echo $'0\t0\t*\t*\t*\troot\t/bin/lock' >> /etc/crontab
  touch $SEMAPHORE
fi
