#!/bin/bash
# Firstrun setup for Raspberry Pi. Copied to /etc/init.d/firstrun
### BEGIN INIT INFO
# Provides:          firstrun
# Required-Start:    $networking
# Required-Stop:     $networking
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO

LIBNFCDIR=/home/pi/libnfc-1.7.1/
MAINDIR=/home/pi/src/vnw/main/
GODIR=/home/pi/go/
GOPATH=/home/pi/
SEMAPHORE=/var/opt/vnw-run
PASSWORD=/home/pi/password
if [ ! -f $SEMAPHORE ]
then
	# Set password
	cat $PASSWORD $PASSWORD | passwd -q pi
	rm -f $PASSWORD
  # Install our deps
	apt-get -q -y update
	export DEBIAN_FRONTEND=noninteractive
	apt-get -q -y install libusb-dev daemontools vim bzr mercurial wicd-cli tmux unattended-upgrades lsof
	# Install libnfc
	cd $LIBNFCDIR
	$LIBNFCDIR/configure
	make
	make install
	ldconfig
	depmod
	# Make a custom go, if we don't have the proper version.
	$GODIR/bin/go --version 2> /dev/null
	if [[ $? -ne 2 ]]
	then
		cd $GODIR/src/
		./make.bash
	fi
	# Make and install our main program.
	cd $MAINDIR
	echo "Compiling Main"
	GOPATH=$GOPATH $GODIR/bin/go build main.go
	GOPATH=$GOPATH $GODIR/bin/go build nonfc.go
	install main /bin/main
  install ../scripts/lock /bin/
  install ../scripts/unlock /bin/
  
  # Scripts to make things run.
  echo "America/Los_Angeles" > /etc/timezone
  dpkg-reconfigure --frontend noninteractive tzdata
  # This is about the only non-idempotent thing in here.
	echo "use_settings_globally = 1" >> /etc/wicd/manager-settings.conf
  echo $'0\t0\t*\t*\t*\troot\t/bin/lock' >> /etc/crontab
	echo "export GOPATH=/home/pi/" >> /home/pi/.bashrc
	echo "alias go=$GODIR/bin/go" >> /home/pi/.bashrc
	echo "if [[ \`tty\` == \"/dev/tty1\" ]]" >> /home/pi/.bashrc
	echo "then" >> /home/pi/.bashrc
  echo "tmux new-session -s screen" >> /home/pi/.bashrc
  echo "fi" >> /home/pi/.bashrc

  touch $SEMAPHORE
fi

# Start our program.
svscanboot &
exit 0
